version: '3.8'

services:

  admin:
    build: ./admin
    container_name: admin-app
    ports:
      - "8081:80"
    volumes:
      - ./admin:/var/www/html
    depends_on:
      - db
    networks:
      - app-net
    user: "www-data"

  patient:
    build: ./patient
    container_name: patient-app
    ports:
      - "8082:80"
    volumes:
      - ./patient:/var/www/html
    depends_on:
      - db
    networks:
      - app-net
    user: "www-data"

  staff:
    build: ./staff
    container_name: staff-app
    ports:
      - "8083:80"
    volumes:
      - ./staff:/var/www/html
    depends_on:
      - db
    networks:
      - app-net
    user: "www-data"

  appointment-service:
    build: ./services/appointment-service
    container_name: appointment-service
    ports:
      - "8084:80"
    volumes:
      - ./services/appointment-service:/var/www/html
    depends_on:
      - db-appointment
    networks:
      - app-net
    user: "www-data"

  ward-service:
    build: ./services/ward-service
    container_name: ward-service
    ports:
      - "8085:80"
    volumes:
      - ./services/ward-service:/var/www/html
    depends_on:
      - db-ward
    networks:
      - app-net
    user: "www-data"

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_manage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

  db-appointment:
    image: mysql:5.7
    container_name: mysql-appointment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: appointment_user
      MYSQL_PASSWORD: appointment_pass
    ports:
      - "3307:3306"
    volumes:
      - db_appointment_data:/var/lib/mysql
    networks:
      - app-net

  db-ward:
    image: mysql:5.7
    container_name: mysql-ward
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ward_db
      MYSQL_USER: ward_user
      MYSQL_PASSWORD: ward_pass
    ports:
      - "3308:3306"
    volumes:
      - db_ward_data:/var/lib/mysql
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_ARBITRARY: 1
    networks:
      - app-net

volumes:
  db_data:
  db_appointment_data:
  db_ward_data:

networks:
  app-net:
