version: '3.8'

services:
  admin:
    build: ./admin
    container_name: admin-app
    ports:
      - "8081:80"
    volumes:
      - ./admin:/var/www/html
    depends_on:
      - db
    networks:
      - app-net

  patient:
    build: ./patient
    container_name: patient-app
    ports:
      - "8082:80"
    volumes:
      - ./patient:/var/www/html
    depends_on:
      - db
    networks:
      - app-net

  staff:
    build: ./staff
    container_name: staff-app
    ports:
      - "8083:80"
    volumes:
      - ./staff:/var/www/html
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_manage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
