services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./admin:/var/www/html/admin
      - ./patient:/var/www/html/patient
      - ./staff:/var/www/html/staff
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_manage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
